### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by iDVB** [falti/dotenv-action#12]
Not sure what I'm doing wrong, but neither the upper or lower cases seem to net out with any values?

**.env**
```
GATSBY_SITE_URL = "https://test.domain.com"
GATSBY_STACKNAME = "brand-x-feat-submit"
```

**workflow.yml**
```
...
      - name: Slurp Up .env
        uses: falti/dotenv-action@v0.2.5

      - name: Test
        run: |
          echo "${{ steps.dotenv.outputs.gatsby_site_url }}"
          echo "${{ steps.dotenv.outputs.gatsby_stackname }}"
...
```

**Also tried...which btw, feels more intuitive, not sure why it should lowercase them?**
```
...
      - name: Slurp Up .env
        uses: falti/dotenv-action@v0.2.5

      - name: Test
        run: |
          echo "${{ steps.dotenv.outputs.GATSBY_SITE_URL }}"
          echo "${{ steps.dotenv.outputs.GATSBY_STACKNAME }}"
...
```

**Error:**
![image](https://user-images.githubusercontent.com/189506/112686457-59c9fb00-8e4c-11eb-8914-9907d30e3b31.png)

**Comment by falti** [comment]
remove the whitespace between the '='

**Comment by iDVB** [comment]
Actually it was even dummer than that on my part. 
I hadn't given that step an ID and yet I was trying to ref it...
`id: dotenv`

FIXED and now works the charm! thanks!
