### ISSUE TITLE
Select his own file instead of .env file

### ISSUE THREAD

**Issue by flenoir** [falti/dotenv-action#17]
Hi, 

Thanks for this great action that works fine. 

As i'm using terraform and tfvars files, there's a duplication in defining environnemnt variables as i need to use a .env file now. 

Would it be possible to be able to select my own file and path which contains variables ? with a different name than .env ?

**Comment by ljoks** [comment]
see readme

`path` input

Override the path to the .env file. Default is .env in the repository root.

**Comment by falti** [comment]
Thanks @ljoks for the answer. Closing the issue.
