### ISSUE TITLE
file does not exist

### ISSUE THREAD

**Issue by DennisMuchiri** [falti/dotenv-action#19]
Hello @falti @oschlegel @falti where I'm I supposed to place my .env file? I am Getting file does not exist error. my folder structure looks like:
reporoot
&nbsp;&nbsp;.github
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;workflows
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;githubaction.yml   _--i'm reading the .env from here_
.env _--this is the .env file_

  
Please help.

**Comment by DennisMuchiri** [comment]
Getting file does not exist error

**Comment by copydigital** [comment]
Hi Dennis,

by the docs the reporoot is the default file location. Is the file present in the branch you put your action in? I tested and it works here.

**Comment by DennisMuchiri** [comment]
@copydigital my bad - i forgot to put

`uses: actions/checkout@v2.1.1`

before using dotenv to read my .env file. Closing
