### ISSUE TITLE
GitHub Actions: `set-output` command is deprecated

### ISSUE THREAD

**Issue by vlukashov** [falti/dotenv-action#33]
Starting from October, 11th 2022 using the latest version of this action (`falti/dotenv-action@v0.2.7`) yields deprecation warnings:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It looks like simply upgrading the `@actions/core` dependency to `1.10.0` or newer should fix this issue.

**Comment by falti** [comment]
Dependabot also recommended upgrading `@actions/core` which I just did. I am not using the action myself anymore. Please report if there's still any issues.
Thanks for the suggestions and the pull request! Some recent changes have been included and I release v1.0.0
