### ISSUE TITLE
'set-output' command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by nsalfos** [falti/dotenv-action#37]
Imported your actions, but it seems they are still using the deprecated format for output when using it in the workflow it would prompt the warning:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

Think you can review and update? 
nice action btw

**Comment by falti** [comment]
Too busy right now, if you need it quick please send pull request

**Comment by Jessseee** [comment]
In case you are still looking for an alternative `grep KEY .env >> $GITHUB_ENV` or `greb . .env >> $GITHUB_ENV` also does the job. As per the [GitHub documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable).

**Comment by alexrygalov** [comment]
👋 I rebuilt dist file with the new version of core lib from https://github.com/falti/dotenv-action/commit/75886fcb5bfd711b865169431214ace5450f01c3, worked for me. Please check https://github.com/falti/dotenv-action/pull/38
