### ISSUE TITLE
Exporting environment variables makes their names lowercase

### ISSUE THREAD

**Issue by kirsanium** [falti/dotenv-action#47]
Using `export-variables: true` makes the name of variable lowercase inside following steps.
i.e. `WEB_PORT` -> `web_port`, so you can't refer to it as `${WEB_PORT}` how you would expect.

**Expected behaviour**: exporting environment variables keeps casing of their names.

Related to #42.

**Comment by kirsanium** [comment]
Oh sorry, I didn't see `keys-case` option. Closing obviously.

**Comment by kirsanium** [comment]
Why `keys-case: bypass` is not the default behaviour though?

**Comment by falti** [comment]
Simply because the original behavior was like that and I don't want to introduce breaking changes
