### ISSUE TITLE
Timeline for upgrade to Node 20?

### ISSUE THREAD

**Issue by Gipetto** [falti/dotenv-action#50]
GitHub has deprecated Node 16 in GH Actions. Do you have a timeline for upgrading before their "spring 2024" deadline for the switchover?

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by ddnexus** [comment]
It is failing already!

**Comment by Gipetto** [comment]
So, anyone that's looking at this issue, are you switching to something else? And if so, what?

**Comment by falti** [comment]
There are some issues with the pull request. I don't have access to my computer right now, perhaps you can help to fix the problems and I can merge/release it then. 
Thanks!

**Comment by falti** [comment]
New version is available. Please try it and thanks for using my software!
