### ISSUE TITLE
Can an option be added to prefix exported envs?

### ISSUE THREAD

**Issue by benlei** [falti/dotenv-action#54]
For example if I have an .env with:

```
foo=123
```

I may want to export the env variables with the prefix `TF_VAR_` so that Terraform can automatically process the `foo` variable... as well as be able to reference the `step.my-step.outputs.foo` in my workflow.

**Comment by falti** [comment]
Isn't it more comprehensible to just name the variables including the prefix?

**Comment by benlei** [comment]
I think that can work too, but I also use the same `.env` file for non-terraform workflows... which can confuse other engineers (including my future self) for why we're using TF vars in a non-TF vars context.

For example let's say I have an `.env-dev` with:

```
datadog_api_key: 123
```

My team would like to use this API key for terraform to configure DataDog monitors... but at the same time we have other workflows which use this same DataDog API key when configuring/deploying our application (so that our application's metrics can be sent to DataDog).

If this was named instead

```
TF_VARS_datadog_api_key: 123
```

It would seem a bit odd to reference the environment variable/output `TF_VARS_datadog_api_key` - especially when the other workflows aren't utilizing terraform. We could duplicate the variable, but then we'd have to maintain two lines of the same data. We could also duplicate the .env file - one for terraform, one for not-terraform... but then we have to maintain two files.

It would be a huge convenience factor if we had the ability to use the same env file for both terraform and our other workflows.

**Comment by falti** [comment]
Thanks for the PR
